version: "3.9"
services:
  database:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./tmp/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/testapp
    ports:
      - "3000:3000"
    depends_on:
      - database