# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/federated_states', type: :request do
  # FederatedState. As you add validations to FederatedState, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      FederatedState.create! valid_attributes
      get federated_states_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      federated_state = FederatedState.create! valid_attributes
      get federated_state_url(federated_state)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_federated_state_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      federated_state = FederatedState.create! valid_attributes
      get edit_federated_state_url(federated_state)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new FederatedState' do
        expect do
          post federated_states_url, params: { federated_state: valid_attributes }
        end.to change(FederatedState, :count).by(1)
      end

      it 'redirects to the created federated_state' do
        post federated_states_url, params: { federated_state: valid_attributes }
        expect(response).to redirect_to(federated_state_url(FederatedState.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new FederatedState' do
        expect do
          post federated_states_url, params: { federated_state: invalid_attributes }
        end.to change(FederatedState, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post federated_states_url, params: { federated_state: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested federated_state' do
        federated_state = FederatedState.create! valid_attributes
        patch federated_state_url(federated_state), params: { federated_state: new_attributes }
        federated_state.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the federated_state' do
        federated_state = FederatedState.create! valid_attributes
        patch federated_state_url(federated_state), params: { federated_state: new_attributes }
        federated_state.reload
        expect(response).to redirect_to(federated_state_url(federated_state))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        federated_state = FederatedState.create! valid_attributes
        patch federated_state_url(federated_state), params: { federated_state: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested federated_state' do
      federated_state = FederatedState.create! valid_attributes
      expect do
        delete federated_state_url(federated_state)
      end.to change(FederatedState, :count).by(-1)
    end

    it 'redirects to the federated_states list' do
      federated_state = FederatedState.create! valid_attributes
      delete federated_state_url(federated_state)
      expect(response).to redirect_to(federated_states_url)
    end
  end
end
